// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `io.zzstoatzz.status` namespace.
pub mod record;
#[derive(Debug)]
pub struct Record;
impl atrium_api::types::Collection for Record {
    const NSID: &'static str = "io.zzstoatzz.status.record";
    type Record = record::Record;
}
