// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!A collection of known record types.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum KnownRecord {
    #[serde(rename = "io.zzstoatzz.status.record")]
    LexiconsIoZzstoatzzStatusRecord(Box<crate::lexicons::io::zzstoatzz::status::record::Record>),
}
impl From<crate::lexicons::io::zzstoatzz::status::record::Record> for KnownRecord {
    fn from(record: crate::lexicons::io::zzstoatzz::status::record::Record) -> Self {
        KnownRecord::LexiconsIoZzstoatzzStatusRecord(Box::new(record))
    }
}
impl From<crate::lexicons::io::zzstoatzz::status::record::RecordData> for KnownRecord {
    fn from(record_data: crate::lexicons::io::zzstoatzz::status::record::RecordData) -> Self {
        KnownRecord::LexiconsIoZzstoatzzStatusRecord(Box::new(record_data.into()))
    }
}
impl From<KnownRecord> for atrium_api::types::Unknown {
    fn from(val: KnownRecord) -> Self {
        atrium_api::types::TryIntoUnknown::try_into_unknown(&val).unwrap()
    }
}
