// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `xyz.statusphere` namespace.
pub mod status;
#[derive(Debug)]
pub struct Status;
impl atrium_api::types::Collection for Status {
    const NSID: &'static str = "xyz.statusphere.status";
    type Record = status::Record;
}
