name: Deploy Review App
on:
  # Run this workflow on every PR event. Existing review apps will be updated when the PR is updated.
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths:
      - 'src/**'
      - 'templates/**'
      - 'static/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'Dockerfile'
      - 'fly.toml'
      - 'fly.review.toml'
      - 'build.rs'
      - 'sqlx-data.json'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  # Set these to your Fly.io organization and preferred region.
  FLY_REGION: ewr
  FLY_ORG: personal

jobs:
  review_app:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}

    # Deploying apps with this "review" environment allows the URL for the app to be displayed in the PR UI.
    environment:
      name: review
      # The script in the `deploy` sets the URL output for each review app.
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Deploy PR app to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.1
        with:
          name: zzstoatzz-status-pr-${{ github.event.number }}
          config: fly.review.toml
          # Use smaller resources for review apps
          vmsize: shared-cpu-1x
          memory: 256
          # Set OAUTH_REDIRECT_BASE and APP_URL dynamically for OAuth redirects
          secrets: |
            OAUTH_REDIRECT_BASE=https://zzstoatzz-status-pr-${{ github.event.number }}.fly.dev
            APP_URL=https://zzstoatzz-status-pr-${{ github.event.number }}.fly.dev